---
- name: Installer Apache sur Docker Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
